config/routes.rb
Ticket2::Application.routes.draw do
  resources :owners

  resources :categories

  resources :codes

  resources :priorities

  resources :updates

  resources :tickets

  resources :users do
    member do
      get :tickets
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

root :to => "pages#home"

end

app/models/priority.rb
class Priority < ActiveRecord::Base

  has_many :tickets
  
  default_scope :order => 'priorities.level ASC'

end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController

  before_filter :admin_user
  
  # GET /priorities
  # GET /priorities.xml
  def index
    @priorities = Priority.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @priorities }
    end
  end

  # GET /priorities/1
  # GET /priorities/1.xml
  def show
    @priority = Priority.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @priority }
    end
  end

  # GET /priorities/new
  # GET /priorities/new.xml
  def new
    @priority = Priority.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @priority }
    end
  end

  # GET /priorities/1/edit
  def edit
    @priority = Priority.find(params[:id])
  end

  # POST /priorities
  # POST /priorities.xml
  def create
    @priority = Priority.new(params[:priority])

    respond_to do |format|
      if @priority.save
        format.html { redirect_to(@priority, :notice => 'Priority was successfully created.') }
        format.xml  { render :xml => @priority, :status => :created, :location => @priority }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @priority.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /priorities/1
  # PUT /priorities/1.xml
  def update
    @priority = Priority.find(params[:id])

    respond_to do |format|
      if @priority.update_attributes(params[:priority])
        format.html { redirect_to(@priority, :notice => 'Priority was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @priority.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /priorities/1
  # DELETE /priorities/1.xml
  def destroy
    @priority = Priority.find(params[:id])
    @priority.destroy

    respond_to do |format|
      format.html { redirect_to(priorities_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/views/priorities/_form.html.erb
<%= form_for(@priority) do |f| %>
  <% if @priority.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@priority.errors.count, "error") %> prohibited this priority from being saved:</h2>

      <ul>
      <% @priority.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priorities/_priority.html.erb
<%= priority.priority %> [<%= priority.level %>]

app/views/priorities/edit.html.erb
<h1>Editing priority</h1>

<%= render 'form' %>

<%= link_to 'Show', @priority %> |
<%= link_to 'Back', priorities_path %>

app/views/priorities/index.html.erb
<h1>Listing priorities</h1>

<table>
  <tr>
    <th>Level</th>
    <th>Priority</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @priorities.each do |priority| %>
  <tr>
    <td><%= priority.level %></td>
    <td><%= priority.priority %></td>
    <td><%= priority.description %></td>
    <td><%= link_to 'Show', priority %></td>
    <td><%= link_to 'Edit', edit_priority_path(priority) %></td>
    <td><%= link_to 'Destroy', priority, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Priority', new_priority_path %>

app/views/priorities/new.html.erb
<h1>New priority</h1>

<%= render 'form' %>

<%= link_to 'Back', priorities_path %>

app/views/priorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Level:</b>
  <%= @priority.level %>
</p>

<p>
  <b>Priority:</b>
  <%= @priority.priority %>
</p>

<p>
  <b>Description:</b>
  <%= @priority.description %>
</p>


<%= link_to 'Edit', edit_priority_path(@priority) %> |
<%= link_to 'Back', priorities_path %>