config/routes.rb
Ticket2::Application.routes.draw do
  resources :owners

  resources :categories

  resources :codes

  resources :priorities

  resources :updates

  resources :tickets

  resources :users do
    member do
      get :tickets
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

root :to => "pages#home"

end

app/models/update.rb
class Update < ActiveRecord::Base

  belongs_to :ticket
  belongs_to :code
  belongs_to :user
  
  default_scope :order => 'updates.created_at DESC'

end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController

  before_filter :authenticate

  # GET /updates
  # GET /updates.xml
  def index
    @updates = Update.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @updates }
    end
  end

  # GET /updates/1
  # GET /updates/1.xml
  def show
    @update = Update.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @update }
    end
  end

  # GET /updates/new
  # GET /updates/new.xml
  def new
    @update = Update.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @update }
    end
  end

  # GET /updates/1/edit
  def edit
    @update = Update.find(params[:id])
  end

  # POST /updates
  # POST /updates.xml
  def create
    @update = Update.new(params[:update])
    @update.comment += ' ' + @update.code.description
    @update.save
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  # PUT /updates/1
  # PUT /updates/1.xml
  def update
    @update = Update.find(params[:id])

    respond_to do |format|
      if @update.update_attributes(params[:update])
        format.html { redirect_to(@update, :notice => 'Update was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @update.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.xml
  def destroy
    @update = Update.find(params[:id])
    @update.destroy

    respond_to do |format|
      format.html { redirect_to(updates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/updates_helper.rb
module UpdatesHelper

end

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id %><br />
    <%= f.text_field :ticket_id %>
  </div>
  <div class="field">
    <%= f.label :code_id %><br />
    <%= f.text_field :code_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/_update.html.erb
  <tr>
    <td><%= update.ticket.sent_by.last.name %></td>
    <td><%= update.ticket.sent_to.last.name %></td>
    <td><%= update.ticket.title %></td>
    <td><%= render update.code %></td>
    <td><%= update.comment %></td>
    <td><%= update.user.name %>, <%= time_ago_in_words(update.created_at) %> ago</td>
    <td>
    <% if current_user.admin? %>
      [&nbsp;<%= link_to 'Show', update.ticket %> 
      <%= link_to 'Edit', edit_update_path(update) %> 
      <%= link_to 'Destroy', update, :confirm => 'Are you sure?', :method => :delete %>&nbsp;]
  <% end %>
    </td>
  </tr>

app/views/updates/_update_set.html.erb
<table>
  <thead>
    <th>From</th>
    <th>To</th>
    <th>Ticket</th>
    <th>Code</th>
    <th>Comment</th>
    <th>Update By</th>
    <th></th>
  </thead>
  <tbody>
    <%= render @updates %>
  </tbody>
</table>

app/views/updates/create.js.erb
$('code').update('<%= escape_javascript(render(@update.code)) + "[ #{@update.comment} ]" %>');

app/views/updates/edit.html.erb
<h1>Editing update</h1>

<%= render 'form' %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<h1>updates</h1>

<%= render 'updates/update_set' %>

<%= link_to 'New Update', new_update_path %>

app/views/updates/new.html.erb
<h1>New update</h1>

<%= render 'form' %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ticket:</b>
  <%= @update.ticket.title %>
</p>

<p>
  <b>Code:</b>
  <%= @update.code.code %>
</p>

<p>
  <b>Comment:</b>
  <%= @update.comment %>
</p>

<p>
  <b>Comment by:</b>
  <%= @update.user.name %>
</p>


<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>