config/routes.rb
Ticket2::Application.routes.draw do
  resources :owners

  resources :categories

  resources :codes

  resources :priorities

  resources :updates

  resources :tickets

  resources :users do
    member do
      get :tickets
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<footer>
  <%= render 'layouts/menu' %>
  <p>Design and development &copy; 2011, John Brown</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= render 'layouts/menu' %>
</header>

app/views/layouts/_menu.html.erb
<ul class="menu">
  <% if signed_in? %>
  <li><%= current_user.name + ', ' + current_user.email %></li>
  <li><%= link_to 'home', root_path  %></li>
  <li>|</li>
  <% end %>
  <li><%= link_to 'New Ticket', new_ticket_path %></li>
  <% if signed_in? %>
    <% if current_user.admin? %>
    <li><%= link_to 'users', users_path %></li>
    <li><%= link_to 'tickets', tickets_path %></li>
    <li><%= link_to 'updates', updates_path %></li>
    <li><%= link_to 'owners', owners_path %></li>
    <li><%= link_to 'priorities', priorities_path %></li>
    <li><%= link_to 'codes', codes_path %></li>
    <li><%= link_to 'categories', categories_path %></li>
  <% end %>
  <li>|</li>
    <li><%= link_to 'Sign out', signout_path, :method => :delete %>
  <% else %>
  <li><%= link_to "Sign in", signin_path %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticket2</title>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
  
  <%= debug(params) if Rails.env.development? %>
</body>
</html>